# Generated by Django 4.0.2 on 2022-02-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tboxd', '0002_remove_film_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='name',
        ),
    ]
