# Generated by Django 4.0.2 on 2022-02-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tboxd', '0003_rename_title_film_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.CharField(default='https://letterboxd.com/', max_length=256),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
