# Generated by Django 4.0.2 on 2022-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tboxd', '0004_film_url_alter_film_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='name',
        ),
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default=models.CharField(max_length=32, primary_key=True, serialize=False), max_length=64),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
